Repository QuantStack/jupyter-drives, pull requests merged in 2023-11, with the labels that each got.

#2 Add a dialog to select drives
  package.json
  schema/widget.json
  src/drivelistmanager.tsx
  src/icons.ts
  src/index.ts
  src/svg.d.ts
  style/base.css
  style/drive.svg
  yarn.lock
Labels: feature

#4 Fix for adding drives
  src/drivelistmanager.tsx
Labels: bug

#3 Set up backend structure and list all available drives
  conftest.py
  jupyter_drives/__init__.py
  jupyter_drives/base.py
  jupyter_drives/handlers.py
  jupyter_drives/log.py
  jupyter_drives/managers/__init__.py
  jupyter_drives/managers/manager.py
  jupyter_drives/managers/s3.py
  jupyter_drives/tests/test_extensions.py
  jupyter_drives/tests/test_handlers.py
  pyproject.toml
  src/index.ts
  tsconfig.json
Labels: enhancement

#6 Fix logger initialization in listing available drives API handler
  jupyter_drives/handlers.py
Labels: bug
